Northwind_John/Northwind_John/Models/partial/user.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Northwind_John.Models
{
   [MetadataType(typeof(userMetadata))]
   public partial class user
   {
      public class userMetadata
      {
         public int user_id { get; set; }
         [DisplayName("姓名")]
         public string user_name { get; set; }
         public int dept_id { get; set; }
         [DisplayName("更新時間")]
         public string update_date { get; set; }
         public virtual dept dept { get; set; }
      }
   }
}

Northwind_John/Northwind_John/Models/user.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind_John.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string user_name { get; set; }
        public int dept_id { get; set; }
        public string update_date { get; set; }
    
        public virtual dept dept { get; set; }
    }
}

Northwind_John/Northwind_John/Controllers/deptsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Northwind_John.Models;
using Northwind_John.ViewModel;

namespace Northwind_John.Controllers
{
   public class deptsController : Controller
   {
      private ModelContainer db = new ModelContainer();

      // GET: depts
      public ActionResult Index()
      {
         depViewModel dep = new depViewModel();
         dep.depts = db.deptSet.ToList();
         return View(dep);
      }

      // GET: depts/Details/5
      public ActionResult Details(int? id)
      {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dept dept = db.deptSet.Find(id);
         if (dept == null) {
            return HttpNotFound();
         }
         return View(dept);
      }

      // GET: depts/Create
      public ActionResult Create()
      {
         return PartialView();
      }

      // POST: depts/Create
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "dept_id,dept_name")] depViewModel dept)
      {
         if (ModelState.IsValid) {
            db.deptSet.Add(dept.deptfile);
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         
         return PartialView(dept.deptfile);
      }

      // GET: depts/Edit/5
      public ActionResult Edit(int? id)
      {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dept dept = db.deptSet.Find(id);
         if (dept == null) {
            return HttpNotFound();
         }
         return View(dept);
      }

      // POST: depts/Edit/5
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "dept_id,dept_name")] dept dept)
      {
         if (ModelState.IsValid) {
            db.Entry(dept).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(dept);
      }

      // GET: depts/Delete/5
      public ActionResult Delete(int? id)
      {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         dept dept = db.deptSet.Find(id);

         if (dept == null) {
            return HttpNotFound();
         }
         db.deptSet.Remove(dept);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         if (disposing) {
            db.Dispose();
         }
         base.Dispose(disposing);
      }
   }
}

Northwind_John/Northwind_John/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Northwind_John.Models;

namespace Northwind_John.Controllers
{
   public class usersController : Controller
   {
      private ModelContainer db = new ModelContainer();

      // GET: users
      public ActionResult Index(string Genre, string searchString)
      {
         //https://dotblogs.com.tw/berrynote/2016/08/26/000310
         //Index方法新增了一個叫做Genre的參數。在前幾行的程式碼中，先建立了一個List與查詢所有部門(Genre)的LINQ。 
         var GenreLst = new List<string>();
         
         var GenreQry = from d in db.userSet
                        orderby d.dept.dept_name
                        select d.dept.dept_name;
         //AddRange方法將剛剛GenreQry查詢出來的資料( Distinct()方法避免重複的部門 )加入GenreLst，再將GenreLst儲存到ViewBag.Genre。
         //而下面的程式碼中，會先檢查Genre是否為空或是Null。若有值則加入Where條件，依照Genre篩選員工。
         GenreLst.AddRange(GenreQry.Distinct());
         ViewBag.Genre = new SelectList(GenreLst);

         var users = from m in db.userSet
                      select m;

         if (!String.IsNullOrEmpty(searchString)) {
            users = users.Where(s => s.user_name.Contains(searchString));
         }

         if (!string.IsNullOrEmpty(Genre)) {
            users = users.Where(x => x.dept.dept_name == Genre);
         }
         //var userSet = db.userSet.Include(u => u.dept);
         return View(users);
      }

      // GET: users/Details/5
      public ActionResult Details(int? id)
      {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         user user = db.userSet.Find(id);
         if (user == null) {
            return HttpNotFound();
         }
         return PartialView(user);
      }

      // GET: users/Create
      public ActionResult Create()
      {
         ViewBag.dept_id = new SelectList(db.deptSet, "dept_id", "dept_name");
         return View();
      }

      // POST: users/Create
      // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
      // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "user_id,user_name,dept_id,update_date")] user user)
      {
         if (ModelState.IsValid) {
            user.update_date = DateTime.Now.ToString();
            db.userSet.Add(user);
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         ViewBag.dept_id = new SelectList(db.deptSet, "dept_id", "dept_name", user.dept_id);
         return PartialView(user);
      }

      // GET: users/Edit/5
      public ActionResult Edit(int? id)
      {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         user user = db.userSet.Find(id);
         if (user == null) {
            return HttpNotFound();
         }
         ViewBag.dept_id = new SelectList(db.deptSet, "dept_id", "dept_name", user.dept_id);
         return View(user);
      }

      // POST: users/Edit/5
      // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
      // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "user_id,user_name,dept_id,update_date")] user user)
      {
         if (ModelState.IsValid) {
            user.update_date = DateTime.Now.ToString();
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         ViewBag.dept_id = new SelectList(db.deptSet, "dept_id", "dept_name", user.dept_id);
         return View(user);
      }

      // GET: users/Delete/5
      public ActionResult Delete(int? id)
      {
         if (id == null) {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         user user = db.userSet.Find(id);
         db.userSet.Remove(user);
         db.SaveChanges();
         if (user == null) {
            return HttpNotFound();
         }
         TempData["message"] = "你已刪除" + user.user_name;
         return RedirectToAction("Index");
      }
      
      protected override void Dispose(bool disposing)
      {
         if (disposing) {
            db.Dispose();
         }
         base.Dispose(disposing);
      }
   }
}

Northwind_John/Northwind_John/Views/users/Create.cshtml
@model Northwind_John.Models.user

@{
    ViewBag.Title = "新增";
}
@section style{
    <style>
        @@import url(//fonts.googleapis.com/earlyaccess/notosanstc.css);

        * {
            font-family: 'Noto Sans TC', sans-serif;
            font-size: 18px;
        }
    </style>
}
<h2>新增</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>user</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.user_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.user_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dept_id, "部門", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("dept_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.dept_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="新增" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到清單", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Northwind_John/Northwind_John/Views/users/Details.cshtml
@model Northwind_John.Models.user

@{
    ViewBag.Title = "詳細資料";
}
@section style{
    <style>
        @@import url(//fonts.googleapis.com/earlyaccess/notosanstc.css);

        * {
            font-family: 'Noto Sans TC', sans-serif;
            font-size: 18px;
        }
    </style>
}
<h2>詳細資料</h2>

<div>
    <h4>user</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.user_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.user_name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.update_date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.update_date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dept.dept_name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dept.dept_name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.user_id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Northwind_John/Northwind_John/Views/users/Edit.cshtml
@model Northwind_John.Models.user

@{
    ViewBag.Title = "編輯員工";
}
@section style{
    <style>
        @@import url(//fonts.googleapis.com/earlyaccess/notosanstc.css);

        * {
            font-family: 'Noto Sans TC', sans-serif;
            font-size: 18px;
        }
    </style>
}
<h2>編輯員工</h2>


@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>user</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.user_id)

        <div class="form-group">
            @Html.LabelFor(model => model.user_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.user_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.user_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dept_id, "dept_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("dept_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.dept_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("回到清單", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Northwind_John/Northwind_John/Views/users/Index.cshtml
@model IEnumerable<Northwind_John.Models.user>

@{
    ViewBag.Title = "員工清單";
}
@section style{
    <style>
        @@import url(//fonts.googleapis.com/earlyaccess/notosanstc.css);

        * {
            font-family: 'Noto Sans TC', sans-serif;
            font-size: 18px;
        }
    </style>
}
<h2>員工名單</h2>

<p>
    @Html.ActionLink("新增員工", "Create")
    @Html.ActionLink("新增部門", "Create", "depts")
    @using (Html.BeginForm("Index", "users", FormMethod.Get)) {
    <p>
        部門: @Html.DropDownList("Genre", "All")
        員工: @Html.TextBox("searchString")
        <input type="submit" value="查詢" />
    </p>
}
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.user_name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.update_date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dept.dept_name)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.user_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.update_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dept.dept_name)
                </td>
                <td>
                    @Html.ActionLink("編輯", "Edit", new { id = item.user_id }) |
                    @Html.ActionLink("詳細資料", "Details", new { id = item.user_id }) |
                    @Html.ActionLink("刪除", "Delete", new { id = item.user_id })
                </td>
            </tr>
        }
    </table>

    @if (TempData["message"] != null) {
        <script type="text/javascript">
        var message = @Html.Raw(Json.Encode(TempData["message"]));
            alert(message);
        </script>
    }